import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#bbc6e2",
        "on-background": "#191c1e",
        "primary-fixed": "#d7e2ff",
        "on-secondary-fixed": "#0b1c30",
        "error": "#ba1a1a",
        "on-primary-fixed": "#101b30",
        "on-secondary-fixed-variant": "#38485d",
        "surface-bright": "#f7f9fb",
        tertiary: "#00160c",
        "primary-fixed-dim": "#bbc6e2",
        "tertiary-container": "#002d1d",
        "on-tertiary-fixed": "#002114",
        "on-primary-fixed-variant": "#3c475d",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "on-surface": "#191c1e",
        "outline-variant": "#c5c6cd",
        "on-surface-variant": "#45474d",
        "tertiary-fixed": "#85f8c4",
        "on-primary": "#ffffff",
        background: "#f7f9fb",
        "tertiary-fixed-dim": "#68dba9",
        secondary: "#505f76",
        "surface-container-low": "#f2f4f6",
        "surface-variant": "#e0e3e5",
        outline: "#75777d",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-container": "#54647a",
        "on-primary-container": "#828da7",
        "primary-container": "#1b263b",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        surface: "#f7f9fb",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        "surface-tint": "#545e76",
        "on-error-container": "#93000a",
        "surface-container": "#eceef0",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#1fa072",
        primary: "#051125",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#d0e1fb",
        "on-tertiary-fixed-variant": "#005137",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;